#include <gtest/gtest.h>

#include <array>
#include <cmath>
#include <random>
#include <vector>

#include "dsp/farrow_resampler.hpp"
#include "dsp/source_delay_line.hpp"

using openCREST::dsp::FarrowResampler;
using openCREST::dsp::SourceDelayLine;

// ---------------------------------------------------------------------------
// Sizing & zero-init
// ---------------------------------------------------------------------------

TEST(SourceDelayLine, ResizeIsPowerOfTwo) {
    SourceDelayLine s;
    s.resize(1000);
    // Power-of-two: 1024.
    EXPECT_EQ(s.capacity(), 1024u);
    s.resize(2048);
    EXPECT_EQ(s.capacity(), 2048u);
    s.resize(3);
    EXPECT_EQ(s.capacity(), 4u);
}

TEST(SourceDelayLine, FreshlyResizedIsZeroAndProducerZero) {
    SourceDelayLine s;
    s.resize(64);
    EXPECT_EQ(s.producer_position(), 0u);
    // Read at pos 1.0 should yield 0 (all four neighbours are zero).
    EXPECT_FLOAT_EQ(s.read_at(1.0), 0.0f);
    EXPECT_FLOAT_EQ(s.read_at(2.5), 0.0f);
}

TEST(SourceDelayLine, ClearResetsProducerAndZeroesBuffer) {
    SourceDelayLine s;
    s.resize(64);
    std::vector<float> in(8, 7.0f);
    s.write(in.data(), in.size());
    EXPECT_EQ(s.producer_position(), 8u);

    s.clear();
    EXPECT_EQ(s.producer_position(), 0u);
    // After clear, every slot is zero.
    EXPECT_FLOAT_EQ(s.read_at(3.0), 0.0f);
}

// ---------------------------------------------------------------------------
// Catmull-Rom correctness
// ---------------------------------------------------------------------------

TEST(SourceDelayLine, LinearInterpolationOnRampIsExact) {
    // Catmull-Rom is exact for linear functions.
    SourceDelayLine s;
    s.resize(64);
    std::vector<float> ramp(32);
    for (size_t i = 0; i < ramp.size(); ++i) {
        ramp[i] = static_cast<float>(i);
    }
    s.write(ramp.data(), ramp.size());

    // Interior reads (avoid edges where left/right neighbours wrap).
    for (double pos = 4.0; pos <= 28.0; pos += 0.25) {
        EXPECT_NEAR(s.read_at(pos), static_cast<float>(pos), 1e-3f)
            << "pos=" << pos;
    }
}

TEST(SourceDelayLine, IntegerPositionReturnsExactSample) {
    SourceDelayLine s;
    s.resize(64);
    std::vector<float> in(16);
    for (size_t i = 0; i < in.size(); ++i) in[i] = std::sin(static_cast<float>(i));
    s.write(in.data(), in.size());

    // pos = n (integer) → reads x[n] exactly (mu = 0 → returns history_[1]).
    for (size_t n = 2; n < 14; ++n) {
        EXPECT_NEAR(s.read_at(static_cast<double>(n)), in[n], 1e-5f)
            << "n=" << n;
    }
}

TEST(SourceDelayLine, CubicMatchesFarrowResamplerInterpolate) {
    // Drive both with the same 8-sample window and identical fractional
    // offset; outputs must match bit-for-bit (same Horner form).
    //
    // For FarrowResampler, output[k] is generated by stepping through the
    // input with ratio `r` so we can choose a window where the resampler's
    // history_[0..3] aligns with our SourceDelayLine's x[n-1..n+2] for a
    // known mu.
    std::array<float, 8> samples{
        0.10f, -0.30f, 0.55f, 0.70f, -0.05f, 0.40f, -0.20f, 0.95f
    };

    SourceDelayLine sdl;
    sdl.resize(32);
    sdl.write(samples.data(), samples.size());

    // Run FarrowResampler with ratio=1.0 to get x[n]; restart and use
    // ratio<1 to interpolate at known mu. The cleanest comparison: feed
    // identical 4 sample histories and compare against ours at the same
    // mu.
    //
    // Trick: we manually compute the same Horner formula here so that
    // any matching tolerance is exact for this small dataset (the
    // resampler does the same math internally; running it through
    // .process() introduces output offset / history-state book-keeping
    // that obscures the kernel parity check).
    auto manual_horner = [&](float h0, float h1, float h2, float h3, float mu) {
        return h1 + 0.5f * mu * ((h2 - h0)
            + mu * ((2.0f * h0 - 5.0f * h1 + 4.0f * h2 - h3)
                + mu * (3.0f * (h1 - h2) + h3 - h0)));
    };

    // Compare for n = 1..5, mu in {0.0, 0.3, 0.5, 0.7, 0.99}.
    for (size_t n = 1; n + 2 < samples.size(); ++n) {
        for (double mu : {0.0, 0.3, 0.5, 0.7, 0.99}) {
            const double pos = static_cast<double>(n) + mu;
            const float got      = sdl.read_at(pos);
            const float expected = manual_horner(samples[n - 1], samples[n],
                                                  samples[n + 1], samples[n + 2],
                                                  static_cast<float>(mu));
            EXPECT_FLOAT_EQ(got, expected) << "n=" << n << " mu=" << mu;
        }
    }
}

// ---------------------------------------------------------------------------
// Wrap-around
// ---------------------------------------------------------------------------

TEST(SourceDelayLine, WrapAroundReadsNearProducerRemainCorrect) {
    SourceDelayLine s;
    s.resize(32);  // capacity = 32

    // Write 96 samples (3× capacity) in chunks of 8, then verify reads
    // near the producer cursor are correct (the older history has been
    // overwritten, which is fine; only the last ~24 samples are valid).
    std::mt19937 rng(42);
    std::uniform_real_distribution<float> dist(-1.0f, 1.0f);
    std::vector<float> all_samples(96);
    for (size_t i = 0; i < all_samples.size(); ++i) {
        all_samples[i] = dist(rng);
    }
    for (size_t off = 0; off < all_samples.size(); off += 8) {
        s.write(all_samples.data() + off, 8);
    }
    EXPECT_EQ(s.producer_position(), 96u);

    // The most recent ~capacity-4 samples should still be readable.
    // Test reads near pos 90 (within last 6 samples).
    for (uint64_t n = 88; n < 94; ++n) {
        EXPECT_NEAR(s.read_at(static_cast<double>(n)),
                    all_samples[n], 1e-5f) << "n=" << n;
    }
}

// ---------------------------------------------------------------------------
// Long-stream stability: extended writes don't corrupt the read window.
// ---------------------------------------------------------------------------

TEST(SourceDelayLine, MillionSampleStreamIsStable) {
    SourceDelayLine s;
    s.resize(1024);

    constexpr size_t CHUNK = 256;
    constexpr size_t N     = CHUNK * 4000;  // 1.024 M samples (multiple of CHUNK)
    std::vector<float> chunk(CHUNK);
    for (size_t i = 0; i < chunk.size(); ++i) {
        chunk[i] = std::sin(static_cast<float>(i) * 0.01f);
    }
    for (size_t written = 0; written < N; written += chunk.size()) {
        s.write(chunk.data(), chunk.size());
    }
    EXPECT_EQ(s.producer_position(), N);

    // Read a safe distance below the producer (the last chunk's values are
    // still present in the ring at well-defined positions).
    const double safe_pos = static_cast<double>(N - 4);
    const size_t offset_in_chunk = (N - 4) % chunk.size();
    EXPECT_NEAR(s.read_at(safe_pos), chunk[offset_in_chunk], 1e-5f);
}
